### ISSUE TITLE
Is it working with UIButton?

### ISSUE THREAD

**Issue by ruchiragile** [natrosoft/NAUIViewWithBorders#2]
I can see that, you've made by inheriting `UIView`. What if I want to do the same for UIButton?

**Comment by ruchiragile** [comment]
My bad: `UIButton` <- `UIControl` <- `UIView`. So it should work.

**Comment by n8tr** [comment]
You can place the UIButton within a NAUIViewWithBorders and pin it to each side using constraints.  If you want to try to use the code to make a UIButton do essentially the same thing, go ahead and give it a shot.  However, UIButtons have some weird internal workings that might cause conflicts.  I've tried to subclass UIButtons in the past and ran into various unpredictable issues when trying to manipulate its layout.  Anyway, my first suggestion would be the easiest.
